/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Dominio.Jugador;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Settings extends javax.swing.JDialog {
    Jugador jugador;
    /**
     * Creates new form Settinngs
     * @param parent
     * @param modal
     * @param jugador
     */
    public Settings(java.awt.Frame parent, boolean modal,Jugador jugador) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.jugador=jugador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRojo = new javax.swing.JLabel();
        sldRojo = new javax.swing.JSlider();
        lblVerde = new javax.swing.JLabel();
        sldVerde = new javax.swing.JSlider();
        lblAzul = new javax.swing.JLabel();
        sldAzul = new javax.swing.JSlider();
        txtEjemplo = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblRojo.setText("Rojo = R");

        sldRojo.setMajorTickSpacing(50);
        sldRojo.setMaximum(255);
        sldRojo.setPaintTicks(true);
        sldRojo.setValue(0);
        sldRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRojoStateChanged(evt);
            }
        });

        lblVerde.setText("Verde = G");

        sldVerde.setMajorTickSpacing(50);
        sldVerde.setMaximum(255);
        sldVerde.setPaintTicks(true);
        sldVerde.setValue(0);
        sldVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerdeStateChanged(evt);
            }
        });

        lblAzul.setText("Azul = B");

        sldAzul.setMajorTickSpacing(50);
        sldAzul.setMaximum(255);
        sldAzul.setPaintTicks(true);
        sldAzul.setValue(0);
        sldAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAzulStateChanged(evt);
            }
        });

        txtEjemplo.setEditable(false);
        txtEjemplo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEjemplo.setText("Ejemplo");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sldRojo, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(sldAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRojo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVerde, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAzul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldVerde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEjemplo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRojoStateChanged
        //Actualiza el color
        cambiarColor();
    }//GEN-LAST:event_sldRojoStateChanged

    private void sldVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerdeStateChanged
        //Actualiza el color
        cambiarColor();
    }//GEN-LAST:event_sldVerdeStateChanged

    private void sldAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAzulStateChanged
        //Actualiza el color
        cambiarColor();
    }//GEN-LAST:event_sldAzulStateChanged

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       //Agrega el color a jugador como atributo del ejemplo 
       jugador.setColor(txtEjemplo.getBackground());
       //Se cierra la pestaña
       this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JSlider sldAzul;
    private javax.swing.JSlider sldRojo;
    private javax.swing.JSlider sldVerde;
    private javax.swing.JTextField txtEjemplo;
    // End of variables declaration//GEN-END:variables

    
    //Actualiza el color según se muevan sus parámetros por las flechas
private void cambiarColor() {
        int R, G, B;
        R = sldRojo.getValue();
        G = sldVerde.getValue();
        B = sldAzul.getValue();
        txtEjemplo.setBackground(new Color(R,G,B));
    }

}
